config = {
    'mode': 'train_test',
    'data_path': r'C:\koe\DataCenter\emotic_npy',
    'context_model': 'resnet50',
    'context_model_frozen': True,
    'body_model': 'swin_t',
    'face_model': 'sfer',
    'fuse_model': 'se_fusion',
    'fuse_L': 128,
    'fuse_r': 1,
    'cat_loss_weight': 1,
    'cont_loss_weight': 0,
    'arch': 'multistream',
    'continuous_loss_type': 'L2',
    'discrete_loss_weight_type': 'dynamic',
    'discrete_loss_type': 'bce',
    'learning_rate': 0.001,
    'optimizer': 'Adam',
    'sgd_momentum': 0.5,
    'scheduler': 'exp',
    'warmup': 1000,
    'epochs': 1,
    'batch_size': 32,
}
